# Generated by Django 2.2.4 on 2019-10-09 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0002_auto_20191006_2145'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='choices',
            field=models.ManyToManyField(to='survey.QuestionChoice'),
        ),
    ]
