# Generated by Django 2.2.4 on 2019-10-16 11:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('matrix', '0009_auto_20190924_0832'),
        ('survey', '0003_answer_choices'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='questionchoice',
            options={'ordering': ['value'], 'verbose_name': 'Question choice', 'verbose_name_plural': 'Question choices'},
        ),
        migrations.AddField(
            model_name='survey',
            name='promotionyear',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='matrix.PromotionYear'),
        ),
    ]
