# Generated by Django 2.2.4 on 2019-10-16 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0004_auto_20191016_1329'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='anonymous',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='survey',
            name='allow_anonymous',
            field=models.BooleanField(default=True),
        ),
    ]
