# Generated by Django 2.2.4 on 2020-02-18 17:21

from django.db import migrations, models
import survey.models


class Migration(migrations.Migration):

    dependencies = [
        ("survey", "0006_auto_20191016_1433"),
    ]

    operations = [
        migrations.AddField(
            model_name="survey",
            name="archived",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="question",
            name="question_type",
            field=models.PositiveIntegerField(
                choices=[
                    (0, survey.models.QuestionTypes(0)),
                    (1, survey.models.QuestionTypes(1)),
                    (2, survey.models.QuestionTypes(2)),
                    (3, survey.models.QuestionTypes(3)),
                    (4, survey.models.QuestionTypes(4)),
                    (5, survey.models.QuestionTypes(5)),
                    (6, survey.models.QuestionTypes(6)),
                    (7, survey.models.QuestionTypes(7)),
                ],
                default=survey.models.QuestionTypes(0),
            ),
        ),
    ]
