# Generated by Django 2.2.4 on 2020-02-18 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("survey", "0007_auto_20200218_1821"),
    ]

    operations = [
        migrations.AlterField(
            model_name="survey",
            name="slug",
            field=models.SlugField(max_length=250, unique=True),
        ),
    ]
