# Generated by Django 2.2.10 on 2020-04-30 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("matrix", "0011_auto_20200218_2000"),
    ]

    operations = [
        migrations.CreateModel(
            name="FinalEvaluation",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("added_date", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_date", models.DateTimeField(auto_now=True, null=True)),
                ("name", models.CharField(max_length=150)),
                ("description", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Final evaluation",
                "verbose_name_plural": "Final evaluations",
                "ordering": ["updated_date", "added_date"],
            },
        ),
        migrations.CreateModel(
            name="EvaluationResult",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("added_date", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_date", models.DateTimeField(auto_now=True, null=True)),
                ("filepath", models.CharField(max_length=500)),
                ("downloaded", models.BooleanField(default=False)),
                (
                    "evaluation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="evaluations.FinalEvaluation",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="matrix.ProfileUser",
                    ),
                ),
            ],
            options={
                "verbose_name": "Evaluation result",
                "verbose_name_plural": "Evaluation results",
                "ordering": ["evaluation", "user", "updated_date", "added_date"],
            },
        ),
    ]
