# Generated by Django 2.2.4 on 2019-08-07 21:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ECUE',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_date', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=150)),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name': 'ECUE',
                'ordering': ['ue', 'name'],
            },
        ),
        migrations.CreateModel(
            name='EvaluationValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_date', models.DateTimeField(auto_now=True, null=True)),
                ('value', models.CharField(max_length=10)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Valeur',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='LearningAchievement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_date', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=150)),
                ('slug', models.SlugField(unique=True)),
                ('ecue', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='achievement', to='matrix.ECUE')),
            ],
            options={
                'verbose_name': 'AcquisApprentissage',
                'ordering': ['ecue', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ProfileUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_date', models.DateTimeField(auto_now=True, null=True)),
                ('firstname', models.CharField(max_length=150)),
                ('lastname', models.CharField(max_length=150)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Utilisateur',
            },
        ),
        migrations.CreateModel(
            name='SchoolYear',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_date', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=150)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Annee',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Semestre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_date', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=150)),
                ('order', models.PositiveIntegerField(default=0)),
                ('schoolyear', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='semestres', to='matrix.SchoolYear')),
            ],
            options={
                'verbose_name': 'Semestre',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='UE',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_date', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=150)),
                ('semestre', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ues', to='matrix.Semestre')),
            ],
            options={
                'verbose_name': 'UE',
                'ordering': ['semestre'],
            },
        ),
        migrations.CreateModel(
            name='StudentEvaluation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_date', models.DateTimeField(auto_now=True, null=True)),
                ('teacher_evaluation', models.BooleanField(default=False)),
                ('achievement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matrix.LearningAchievement')),
                ('evaluation_value', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='matrix.EvaluationValue')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matrix.ProfileUser')),
            ],
            options={
                'verbose_name': 'EvaluationEleve',
                'ordering': ['-added_date'],
            },
        ),
        migrations.CreateModel(
            name='SmallClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_date', models.DateTimeField(auto_now=True, null=True)),
                ('ecue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='small_classes', to='matrix.ECUE')),
                ('students', models.ManyToManyField(limit_choices_to={'user__groups__name': 'Élèves'}, related_name='small_classes_student', to='matrix.ProfileUser')),
                ('teacher', models.ForeignKey(limit_choices_to={'user__groups__name': 'Enseignants'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='small_classes_teacher', to='matrix.ProfileUser')),
            ],
            options={
                'verbose_name': 'PetiteClasse',
                'ordering': ['ecue'],
            },
        ),
        migrations.AddField(
            model_name='ecue',
            name='ue',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ecues', to='matrix.UE'),
        ),
    ]
