# Generated by Django 2.2.4 on 2019-08-26 10:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_date', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=150)),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name': 'Course',
                'verbose_name_plural': 'Courses',
                'ordering': ['ecue', 'name'],
            },
        ),
        migrations.CreateModel(
            name='EvaluationValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_date', models.DateTimeField(auto_now=True, null=True)),
                ('value', models.CharField(max_length=10)),
                ('integer_value', models.IntegerField(default=0)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Evaluation value',
                'verbose_name_plural': 'Evaluation values',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='LearningAchievement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_date', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=150)),
                ('slug', models.SlugField(unique=True)),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='achievements', to='matrix.Course')),
            ],
            options={
                'verbose_name': 'Learning achievement',
                'verbose_name_plural': 'Learning achievements',
                'ordering': ['course', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ProfileUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_date', models.DateTimeField(auto_now=True, null=True)),
                ('firstname', models.CharField(max_length=150)),
                ('lastname', models.CharField(max_length=150)),
                ('cesure', models.BooleanField(default=False)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
            },
        ),
        migrations.CreateModel(
            name='PromotionYear',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_date', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=150)),
                ('value', models.PositiveIntegerField(default=0)),
                ('current', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Promotion year',
                'verbose_name_plural': 'Promotion years',
                'ordering': ['value'],
            },
        ),
        migrations.CreateModel(
            name='SchoolYear',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_date', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=150)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'School year',
                'verbose_name_plural': 'School years',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Semestre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_date', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=150)),
                ('order', models.PositiveIntegerField(default=0)),
                ('schoolyear', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='semestres', to='matrix.SchoolYear')),
            ],
            options={
                'verbose_name': 'Semestre',
                'verbose_name_plural': 'Semestres',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='UE',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_date', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=150)),
                ('semestre', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ues', to='matrix.Semestre')),
            ],
            options={
                'verbose_name': 'UE',
                'verbose_name_plural': 'UEs',
                'ordering': ['semestre', 'name'],
            },
        ),
        migrations.CreateModel(
            name='StudentEvaluation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_date', models.DateTimeField(auto_now=True, null=True)),
                ('teacher_evaluation', models.BooleanField(default=False)),
                ('last_evaluation', models.BooleanField(default=False)),
                ('achievement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matrix.LearningAchievement')),
                ('evaluation_value', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='matrix.EvaluationValue')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations_student', to='matrix.ProfileUser')),
            ],
            options={
                'verbose_name': 'Student evaluation',
                'verbose_name_plural': 'Student evaluations',
                'ordering': ['-added_date'],
            },
        ),
        migrations.CreateModel(
            name='SmallClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_date', models.DateTimeField(auto_now=True, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='small_classes', to='matrix.Course')),
                ('promotion_year', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='small_classes', to='matrix.PromotionYear')),
                ('students', models.ManyToManyField(limit_choices_to={'user__groups__name': 'Élèves'}, related_name='small_classes_student', to='matrix.ProfileUser')),
                ('teacher', models.ForeignKey(limit_choices_to={'user__groups__name': 'Enseignants'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='small_classes_teacher', to='matrix.ProfileUser')),
            ],
            options={
                'verbose_name': 'Small class',
                'verbose_name_plural': 'Small classes',
                'ordering': ['course'],
            },
        ),
        migrations.AddField(
            model_name='profileuser',
            name='year_entrance',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='matrix.PromotionYear'),
        ),
        migrations.CreateModel(
            name='ECUE',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_date', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=150)),
                ('ue', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ecues', to='matrix.UE')),
            ],
            options={
                'verbose_name': 'ECUE',
                'verbose_name_plural': 'ECUEs',
                'ordering': ['ue', 'name'],
            },
        ),
        migrations.AddField(
            model_name='course',
            name='ecue',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='matrix.ECUE'),
        ),
    ]

