# Generated by Django 2.2.3 on 2019-07-01 15:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Annee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150)),
                ('ordre', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Semestre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150)),
                ('ordre', models.PositiveIntegerField(default=0)),
                ('annee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='semestres', to='matrix.Annee')),
            ],
        ),
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prenom', models.CharField(max_length=150)),
                ('nom', models.CharField(max_length=150)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UE',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150)),
                ('semestre', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ues', to='matrix.Semestre')),
            ],
        ),
        migrations.CreateModel(
            name='ECUE',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150)),
                ('ue', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ecues', to='matrix.UE')),
            ],
        ),
        migrations.CreateModel(
            name='AcquisApprentissage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150)),
                ('valeurs', models.IntegerField()),
                ('ecue', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acquis', to='matrix.ECUE')),
            ],
        ),
    ]
