# Generated by Django 2.2.3 on 2019-07-01 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matrix', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='annee',
            options={'ordering': ['ordre']},
        ),
        migrations.AlterModelOptions(
            name='semestre',
            options={'ordering': ['ordre']},
        ),
    ]
