# Generated by Django 2.2.4 on 2019-08-30 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matrix', '0002_auto_20190830_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluationvalue',
            name='value',
            field=models.CharField(max_length=150),
        ),
    ]
