# Generated by Django 2.2.3 on 2019-08-09 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matrix', '0002_auto_20190807_2135'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluationvalue',
            name='integer_value',
            field=models.IntegerField(default=0),
        ),
    ]
