# Generated by Django 2.2.3 on 2019-07-01 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matrix', '0002_auto_20190701_1824'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ecue',
            options={'ordering': ['ue', 'nom']},
        ),
        migrations.AlterModelOptions(
            name='ue',
            options={'ordering': ['semestre']},
        ),
    ]
