# Generated by Django 2.2.4 on 2019-09-02 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matrix', '0003_auto_20190830_1627'),
    ]

    operations = [
        migrations.AddField(
            model_name='profileuser',
            name='cas_user',
            field=models.BooleanField(default=True),
        ),
    ]
