# Generated by Django 2.2.3 on 2019-07-01 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matrix', '0003_auto_20190701_1825'),
    ]

    operations = [
        migrations.AddField(
            model_name='ecue',
            name='slug',
            field=models.SlugField(default='', unique=True),
            preserve_default=False,
        ),
    ]
