# Generated by Django 2.2.3 on 2019-07-01 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('matrix', '0004_ecue_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='EchelleValeurs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, default='')),
                ('type_echelle', models.CharField(choices=[(1, 'Entiers'), (2, 'Valeurs')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Valeur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valeur', models.CharField(max_length=10)),
                ('echelle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matrix.EchelleValeurs')),
            ],
        ),
    ]
