# Generated by Django 2.2.4 on 2019-09-12 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matrix', '0005_smallclass_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningachievement',
            name='activated',
            field=models.BooleanField(default=True),
        ),
    ]
