# Generated by Django 2.2.3 on 2019-07-01 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matrix', '0005_echellevaleurs_valeur'),
    ]

    operations = [
        migrations.AlterField(
            model_name='echellevaleurs',
            name='type_echelle',
            field=models.CharField(choices=[('1', 'Entiers'), ('2', 'Valeurs')], max_length=100),
        ),
    ]
