# Generated by Django 2.2.3 on 2019-08-21 07:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('matrix', '0005_auto_20190811_1335'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ue',
            options={'ordering': ['semestre', 'name'], 'verbose_name': 'UE'},
        ),
        migrations.CreateModel(
            name='ECUE',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_date', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=150)),
                ('ue', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ecues', to='matrix.UE')),
            ],
            options={
                'verbose_name': 'ECUE',
                'ordering': ['ue', 'name'],
            },
        ),
    ]
