# Generated by Django 2.2.3 on 2019-07-01 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matrix', '0006_auto_20190701_1911'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='valeur',
            options={'ordering': ['echelle', 'ordre']},
        ),
        migrations.AddField(
            model_name='valeur',
            name='ordre',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
