# Generated by Django 2.2.3 on 2019-08-21 07:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('matrix', '0006_auto_20190821_0917'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['ecue', 'name'], 'verbose_name': 'Course'},
        ),
        migrations.RemoveField(
            model_name='course',
            name='ue',
        ),
        migrations.AddField(
            model_name='course',
            name='ecue',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='matrix.ECUE'),
        ),
    ]
