# Generated by Django 2.2.4 on 2019-09-12 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matrix', '0006_learningachievement_activated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learningachievement',
            name='name',
            field=models.CharField(max_length=250),
        ),
    ]
