# Generated by Django 2.2.3 on 2019-08-21 09:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('matrix', '0007_auto_20190821_0921'),
    ]

    operations = [
        migrations.AddField(
            model_name='profileuser',
            name='schoolyear',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='matrix.SchoolYear'),
        ),
    ]
