# Generated by Django 2.2.4 on 2019-09-12 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matrix', '0007_auto_20190912_1429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learningachievement',
            name='name',
            field=models.CharField(max_length=150),
        ),
    ]
