# Generated by Django 2.2.3 on 2019-07-01 17:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('matrix', '0007_auto_20190701_1914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acquisapprentissage',
            name='valeurs',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='matrix.EchelleValeurs'),
        ),
        migrations.CreateModel(
            name='EvaluationEleve',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acquis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matrix.AcquisApprentissage')),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matrix.Utilisateur')),
                ('valeur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='matrix.Valeur')),
            ],
        ),
    ]
