# Generated by Django 2.2.3 on 2019-08-21 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matrix', '0008_profileuser_school_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profileuser',
            name='schoolyear',
        ),
        migrations.AddField(
            model_name='profileuser',
            name='cesure',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profileuser',
            name='year_entrance',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
