# Generated by Django 2.2.3 on 2019-07-01 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matrix', '0008_auto_20190701_1917'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='acquisapprentissage',
            options={'ordering': ['ecue', 'nom']},
        ),
        migrations.AddField(
            model_name='acquisapprentissage',
            name='slug',
            field=models.SlugField(default='', unique=True),
            preserve_default=False,
        ),
    ]
