# Generated by Django 2.2.3 on 2019-08-22 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matrix', '0009_auto_20190821_1135'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['ecue', 'name'], 'verbose_name': 'Cours'},
        ),
        migrations.AlterModelOptions(
            name='evaluationvalue',
            options={'ordering': ['order'], 'verbose_name': "Valeur de l'évaluation"},
        ),
        migrations.AlterModelOptions(
            name='learningachievement',
            options={'ordering': ['course', 'name'], 'verbose_name': "Acquis d'apprentissage"},
        ),
        migrations.AlterModelOptions(
            name='schoolyear',
            options={'ordering': ['order'], 'verbose_name': 'Année scolaire'},
        ),
        migrations.AlterModelOptions(
            name='smallclass',
            options={'ordering': ['course'], 'verbose_name': 'Petite classe'},
        ),
        migrations.AlterModelOptions(
            name='studentevaluation',
            options={'ordering': ['-added_date'], 'verbose_name': "Évaluation de l'étudiant"},
        ),
    ]
