# Generated by Django 2.2.4 on 2019-10-17 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("matrix", "0009_auto_20190924_0832")]

    operations = [
        migrations.AddField(
            model_name="evaluationvalue",
            name="counts_for_average",
            field=models.BooleanField(default=True),
        )
    ]
