# Generated by Django 2.2.4 on 2019-08-04 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matrix', '0011_auto_20190711_1607'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='valeur',
            options={'ordering': ['ordre']},
        ),
        migrations.RemoveField(
            model_name='acquisapprentissage',
            name='valeurs',
        ),
        migrations.RemoveField(
            model_name='valeur',
            name='echelle',
        ),
        migrations.DeleteModel(
            name='EchelleValeurs',
        ),
    ]
