# Generated by Django 2.2.3 on 2019-08-05 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('matrix', '0013_auto_20190804_2128'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='evaluationeleve',
            options={'ordering': ['-added_date']},
        ),
        migrations.CreateModel(
            name='PetiteClasse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_date', models.DateTimeField(auto_now=True, null=True)),
                ('ecue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='petites_classes', to='matrix.ECUE')),
                ('eleves', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='petites_classes_eleve', to='matrix.Utilisateur')),
                ('enseignant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='petites_classes_enseignant', to='matrix.Utilisateur')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
