# Generated by Django 2.2.4 on 2019-08-07 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matrix', '0014_auto_20190805_1527'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='petiteclasse',
            name='eleves',
        ),
        migrations.AddField(
            model_name='petiteclasse',
            name='eleves',
            field=models.ManyToManyField(related_name='petites_classes_eleve', to='matrix.Utilisateur'),
        ),
    ]
