# Generated by Django 2.2.4 on 2019-08-07 20:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('matrix', '0015_auto_20190807_2048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petiteclasse',
            name='enseignant',
            field=models.ForeignKey(limit_choices_to={'user__groups__name': 'Enseignants'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='petites_classes_enseignant', to='matrix.Utilisateur'),
        ),
    ]
